In [1]:
from sklearn.datasets import make_regression

In [2]:
data = make_regression(n_samples = 1000, n_features = 3, random_state=1000)

In [3]:
data

(array([[ 0.83557405,  0.2794258 ,  1.03009493],
        [-1.07285767,  1.10432848,  0.01674742],
        [-0.39281376,  1.19350677,  0.65612371],
        ...,
        [ 0.00683128, -0.87425121,  0.56318018],
        [ 0.01162881,  0.49707708,  0.65976014],
        [ 0.06724413,  0.16577665,  0.82580827]]),
 array([ 9.95548168e+01,  5.59576767e+01,  1.14242657e+02, -3.55903635e+01,
        -2.28263249e+02,  1.26232459e+02, -4.28769718e+01,  6.88342511e+01,
         1.37558010e+01,  4.29332395e+01,  7.69160906e+01,  6.10896697e+01,
        -4.21858679e+01,  7.11234238e+01,  1.23034688e+02,  5.68735742e+01,
         4.70376037e+01,  9.93767927e+00, -2.84247024e+01, -7.23385626e+01,
         2.87215597e-02, -8.42928206e+01,  4.28411612e+00,  1.41656101e+02,
         3.20266583e+01, -9.47917470e+01, -1.65374753e+02,  5.30271288e+01,
        -7.36705095e+01,  1.79367753e+02, -1.05988526e+02,  2.32687914e+02,
        -1.75040492e+02,  1.49653125e+02, -5.31389794e+01, -1.12994440e+02,
       

In [6]:
data[0][0]

array([0.83557405, 0.2794258 , 1.03009493])

In [7]:
data[1]

array([ 9.95548168e+01,  5.59576767e+01,  1.14242657e+02, -3.55903635e+01,
       -2.28263249e+02,  1.26232459e+02, -4.28769718e+01,  6.88342511e+01,
        1.37558010e+01,  4.29332395e+01,  7.69160906e+01,  6.10896697e+01,
       -4.21858679e+01,  7.11234238e+01,  1.23034688e+02,  5.68735742e+01,
        4.70376037e+01,  9.93767927e+00, -2.84247024e+01, -7.23385626e+01,
        2.87215597e-02, -8.42928206e+01,  4.28411612e+00,  1.41656101e+02,
        3.20266583e+01, -9.47917470e+01, -1.65374753e+02,  5.30271288e+01,
       -7.36705095e+01,  1.79367753e+02, -1.05988526e+02,  2.32687914e+02,
       -1.75040492e+02,  1.49653125e+02, -5.31389794e+01, -1.12994440e+02,
       -1.88684854e+02,  3.21785399e+01, -5.21110736e+01,  8.09616417e+01,
       -1.72209207e+02,  8.36868123e+01,  8.75745769e+01, -2.22684188e+01,
        1.67696496e+02,  2.47169744e+02,  9.91400739e+01, -1.52458217e+02,
       -9.88895926e+01,  8.90808469e+01,  5.99021743e+00, -1.33974841e+01,
       -9.06530117e+01, -

In [8]:
import pandas as pd

In [9]:
features = pd.DataFrame(data[0])

In [10]:
labels = pd.Series(data[1])

In [11]:
features

0         1         2
0    0.835574  0.279426  1.030095
1   -1.072858  1.104328  0.016747
2   -0.392814  1.193507  0.656124
3    0.346936 -1.334251  0.518431
4   -0.554915  0.156717 -3.135381
..        ...       ...       ...
995 -0.496881 -0.059310  0.531478
996 -0.018378 -1.178267 -0.136829
997  0.006831 -0.874251  0.563180
998  0.011629  0.497077  0.659760
999  0.067244  0.165777  0.825808

[1000 rows x 3 columns]

In [12]:
labels

0       99.554817
1       55.957677
2      114.242657
3      -35.590364
4     -228.263249
          ...    
995     31.853294
996    -78.275125
997     -8.584107
998     77.727361
999     71.403559
Length: 1000, dtype: float64

In [13]:
from sklearn.linear_model import SGDRegressor

lr = SGDRegressor()

In [14]:
features['bias'] = 1

In [15]:
features

0         1         2  bias
0    0.835574  0.279426  1.030095     1
1   -1.072858  1.104328  0.016747     1
2   -0.392814  1.193507  0.656124     1
3    0.346936 -1.334251  0.518431     1
4   -0.554915  0.156717 -3.135381     1
..        ...       ...       ...   ...
995 -0.496881 -0.059310  0.531478     1
996 -0.018378 -1.178267 -0.136829     1
997  0.006831 -0.874251  0.563180     1
998  0.011629  0.497077  0.659760     1
999  0.067244  0.165777  0.825808     1

[1000 rows x 4 columns]

In [20]:
import numpy as np

In [17]:
def train(features, labels):
    lr = SGDRegressor()
    lr.fit(features, labels)
    weights = lr.coef_
    return weights

In [18]:
def feedforward(features, weights):
    predictions = np.dot(features, weights.T)
    return predictions

In [19]:
train_weights = train(features, labels)

c:\users\vaibh\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,


In [21]:
linear_predictions = feedforward(features, train_weights)

In [22]:
linear_predictions

array([ 9.95451697e+01,  5.59523544e+01,  1.14231622e+02, -3.55866090e+01,
       -2.28241380e+02,  1.26220537e+02, -4.28732714e+01,  6.88273084e+01,
        1.37550601e+01,  4.29286165e+01,  7.69085511e+01,  6.10839030e+01,
       -4.21818830e+01,  7.11168132e+01,  1.23022779e+02,  5.68680070e+01,
        4.70326478e+01,  9.93636591e+00, -2.84213003e+01, -7.23315544e+01,
        2.89980066e-02, -8.42845728e+01,  4.28363921e+00,  1.41642614e+02,
        3.20237352e+01, -9.47830441e+01, -1.65358288e+02,  5.30218259e+01,
       -7.36630985e+01,  1.79350945e+02, -1.05978766e+02,  2.32665600e+02,
       -1.75022966e+02,  1.49638793e+02, -5.31336979e+01, -1.12983214e+02,
       -1.88666176e+02,  3.21753888e+01, -5.21056631e+01,  8.09537793e+01,
       -1.72192485e+02,  8.36786923e+01,  8.75666630e+01, -2.22657654e+01,
        1.67680175e+02,  2.47145761e+02,  9.91302350e+01, -1.52442725e+02,
       -9.88793145e+01,  8.90727875e+01,  5.98966409e+00, -1.33956345e+01,
       -9.06439999e+01, -